---
- hosts: all
  become: yes

   

  vars:
   - homeDir: /home/ubuntu
   - appDir : yolo
   - packages: ['npm' , 'git', 'docker.io', 'curl']

 
 
  roles:
 #  - mongodb_install
 #  - nginx_setup
    - app_set_up
    - docker_app_build
