

- name: Build the BE app
  command: docker build -t popiyo/ecommerce_be . chdir={{homeDir}}/{{appDir}}/backend



- name: RUN the container
  command: docker run -p 5000:5000 -it -d -e "MONGODB_URI=mongodb://192.168.60.10/yolomy" popiyo/ecommerce_be bin/bash  
