

- name: Build the app
  command: docker build -t popiyo/ecommerce . chdir={{homeDir}}/{{appDir}}/client



- name: RUN the container
  command: docker run -p 80:3000 -it -d  popiyo/ecommerce bin/bash  
