---
- name: Install Packages
  apt: name={{ packages }}  update_cache=yes state=latest
  ignore_errors: yes
     
- name: Create APP Directory
  file: path={{homeDir}}/{{appDir}} state=directory

- name: Clone a repo 
  git:
   repo: https://github.com/Vinge1718/yolo.git
   dest: "{{homeDir}}/{{appDir}}"
   force: yes
  register: git_finished

- name: Running NPM install
  npm: path={{homeDir}}/{{appDir}}/client
  register: npm_finished
  when: git_finished.changed

- name: Build the app
  command: npm run build chdir={{homeDir}}/{{appDir}}/client
  ignore_errors: yes


- name: Prepare the app for static server deployment
  command: npm install -g serve chdir={{homeDir}}/{{appDir}}/client/build
  ignore_errors: yes


- name: Change Persmission to allow Nginx to access the folder 
  file:
    path: "{{homeDir}}/{{appDir}}/client/build"
    mode: 0755


- file:
   path: /etc/nginx/sites-available/default
   state: absent

   
- file:
   path: /etc/nginx/sites-enabled/default
   state: absent
     
- name: create the file to Virtual Host the yolo app
  blockinfile:
   path: /etc/nginx/sites-available/ecommerce
   create: yes
   block: |
    server {
                listen 80;
                server_name 192.168.60.10 localhost 127.0.0.1;
 
                root /home/ubuntu/yolo/client/build;
                index index.html index.htm;
                location / {
                        try_files $uri /index.html;
                }


                location /api {
                  proxy_pass http://localhost:5000/api;
                  proxy_http_version 1.1;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header X-NginX-Proxy true;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                  proxy_cache_bypass $http_upgrade;
                 }

        }


- name: Create symbolic link to Virtual Host file
  file:
   src: /etc/nginx/sites-available/ecommerce
   dest: /etc/nginx/sites-enabled/ecommerce
   state: link


- name: Running NPM install BACKEND
  npm: path={{homeDir}}/{{appDir}}/backend

     
    
- name: Restart Nginx
  systemd:
   state: restarted
   name: nginx
