---


- name: Get Key
  shell: wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
  args:
    executable: /bin/bash

 
- name: List file for Mongo DB
  command: "echo \"deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse\" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list"


- name: Reload Local package database
  command: apt update 


- name: Install MondoDb Packages
  command: apt install -y mongodb-org


- name: Start the Database
  command: systemctl start mongod


- name: Daemon Reload incase of failure
  command: systemctl daemon-reload


- name: Enable System service 
  command: systemctl enable mongod


- lineinfile:
    path: /etc/mongod.conf
    regexp: '^  bindIp: 127.0.0.1'
    line: '  bindIp: 0.0.0.0'
         
    
- name: Restart Mongo
  systemd:
   state: restarted
   name: mongod
